coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: 'reach, diff, flags, files'

flag_management:
  default_rules:
    carryforward: true

flags:
  unit-nuxt:
    paths:
      - apps/web/app/
      - apps/web/server/
      - apps/web/shared/
      - packages/remote-trackers/src/
  e2e-api:
    paths:
      - apps/web/app/
      - apps/web/server/
      - apps/web/shared/
