services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-osi_time_tracker}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pg-osi-time-tracker:/var/lib/postgresql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-osi_time_tracker}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [osi-time-tracker]

  pgadmin:
    image: dpage/pgadmin4:9.16
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - '${PGADMIN_PORT:-8080}:80'
    volumes:
      - pgadmin-osi-time-tracker:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks: [osi-time-tracker]

volumes:
  pg-osi-time-tracker:
  pgadmin-osi-time-tracker:

networks:
  osi-time-tracker:
    name: osi-time-tracker
