import { defineConfig } from 'vite-plus';

export default defineConfig({
  // Root-level tests only; each workspace package keeps its own vitest.config.ts.
  test: {
    name: 'anti-slop',
    include: ['tools/oxlint/anti-slop/test/**/*.{test,spec}.ts'],
    environment: 'node',
  },
  fmt: {
    semi: true,
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    trailingComma: 'all',
    bracketSpacing: true,
    htmlWhitespaceSensitivity: 'ignore',
    endOfLine: 'lf',
    sortPackageJson: false,
    ignorePatterns: [
      '.nuxt',
      '.output',
      'node_modules',
      'dist',
      'pnpm-lock.yaml',
      'apps/migrator/migrations',
      '.junie',
      'AGENTS.md',
      'openspec',
      'pnpm-lock.yaml',
      'pnpm-workspace.yaml',
      'tools/oxlint/anti-slop/index.ts',
      'tools/oxlint/anti-slop/rules/**',
      'tools/oxlint/anti-slop/shared/**',
    ],
  },
  lint: {
    plugins: ['import', 'unicorn'],
    categories: {
      correctness: 'off',
    },
    env: {
      builtin: true,
      browser: true,
      es2024: true,
      node: true,
    },
    settings: {
      'vue-i18n': {
        localeDir: './apps/web/i18n/locales/*.json',
        messageSyntaxVersion: '^9.0.0',
      },
    },
    ignorePatterns: [
      '.nuxt',
      '.output',
      'node_modules',
      'dist',
      'apps/web/.nuxt',
      'apps/web/.output',
      'apps/migrator/migrations',
      'packages/*/dist',
      'tools/oxlint/anti-slop/index.ts',
      'tools/oxlint/anti-slop/rules/**',
      'tools/oxlint/anti-slop/shared/**',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-default': 'error',
      'anti-slop/no-chained-type-assertions': 'error',
      'anti-slop/no-conditional-empty-object-spread': 'error',
      'anti-slop/no-known-value-widening': 'error',
      'anti-slop/no-module-mocking': 'error',
      'anti-slop/no-object-parameters': 'error',
      'anti-slop/no-reflect-apply': 'error',
      'anti-slop/no-reflect-get': 'error',
      'anti-slop/no-runtime-typeof': [
        'error',
        {
          allowInTypeGuards: true,
        },
      ],
      'anti-slop/no-shape-in-symbol-names': 'error',
      'anti-slop/no-unknown-parameters': 'error',
      'anti-slop/no-unknown-returns': 'error',
      'anti-slop/no-unknown-type-aliases': 'error',
      'anti-slop/no-unsafe-dictionary-type': 'error',
      'anti-slop/no-widen-then-assert': 'error',
      'anti-slop/require-safety-comment-for-type-assertion': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts', '**/*.vue'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
          'no-array-constructor': 'error',
          'no-unused-expressions': 'error',
          'no-unused-vars': [
            'error',
            {
              args: 'after-used',
              argsIgnorePattern: '^_',
              ignoreRestSiblings: true,
              vars: 'all',
              varsIgnorePattern: '^_',
            },
          ],
          'no-useless-constructor': 'error',
          'valid-typeof': 'off',
          'typescript/ban-ts-comment': [
            'error',
            {
              minimumDescriptionLength: 10,
            },
          ],
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-empty-object-type': 'error',
          'typescript/no-explicit-any': 'error',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-misused-new': 'error',
          'typescript/no-namespace': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'error',
          'typescript/no-dynamic-delete': 'error',
          'typescript/no-extraneous-class': 'error',
          'typescript/no-invalid-void-type': 'error',
          'typescript/no-non-null-asserted-nullish-coalescing': 'error',
          'typescript/no-non-null-assertion': 'off',
          'typescript/prefer-literal-enum-member': 'error',
          'typescript/unified-signatures': 'error',
          'typescript/consistent-type-imports': [
            'error',
            {
              disallowTypeAnnotations: false,
              prefer: 'type-imports',
            },
          ],
          'typescript/no-import-type-side-effects': 'error',
        },
        plugins: ['typescript'],
      },
      {
        files: ['**/*.vue'],
        rules: {
          'vue/no-arrow-functions-in-watch': 'error',
          'vue/no-async-in-computed-properties': 'error',
          'vue/no-computed-properties-in-data': 'error',
          'vue/no-deprecated-data-object-declaration': 'error',
          'vue/no-deprecated-delete-set': 'error',
          'vue/no-deprecated-destroyed-lifecycle': 'error',
          'vue/no-deprecated-events-api': 'error',
          'vue/no-deprecated-model-definition': 'error',
          'vue/no-deprecated-props-default-this': 'error',
          'vue/no-deprecated-vue-config-keycodes': 'error',
          'vue/no-dupe-keys': 'error',
          'vue/no-export-in-script-setup': 'error',
          'vue/no-expose-after-await': 'error',
          'vue/no-lifecycle-after-await': 'error',
          'vue/no-reserved-component-names': 'error',
          'vue/no-reserved-keys': 'error',
          'vue/no-reserved-props': 'error',
          'vue/no-shared-component-data': 'error',
          'vue/no-side-effects-in-computed-properties': 'error',
          'vue/no-watch-after-await': 'error',
          'vue/prefer-import-from-vue': 'error',
          'vue/require-prop-type-constructor': 'error',
          'vue/require-render-return': 'error',
          'vue/require-slots-as-functions': 'error',
          'vue/return-in-computed-property': 'error',
          'vue/return-in-emits-validator': 'error',
          'vue/valid-define-emits': 'error',
          'vue/valid-define-options': 'error',
          'vue/valid-define-props': 'error',
          'vue/valid-next-tick': 'error',
          'vue/component-definition-name-casing': 'warn',
          'vue/prop-name-casing': 'warn',
          'vue/require-default-prop': 'warn',
          'vue/require-prop-types': 'warn',
          'vue/no-multiple-slot-args': 'warn',
          'vue/no-required-prop-with-default': 'warn',
        },
        plugins: ['vue'],
      },
      {
        files: ['*.yaml', '**/*.yaml', '*.yml', '**/*.yml'],
        rules: {
          'no-irregular-whitespace': 'off',
        },
      },
    ],
    jsPlugins: [
      {
        name: 'anti-slop',
        specifier: './tools/oxlint/anti-slop/index.ts',
      },
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
});
